name: Build and Push Docker Image

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: 1.0.1
  DOCKERHUB_REPOSITORY: formbah/globaljewelries

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build the Docker image
        run: docker build -t $IMAGE_NAME .

      - name: Tag the Docker image
        run: docker tag $IMAGE_NAME $DOCKERHUB_REPOSITORY:$IMAGE_NAME

      - name: Push to Docker Hub
        run: docker push $DOCKERHUB_REPOSITORY:$IMAGE_NAME